services:
  postgres:
    image: postgres:16-alpine
    container_name: shopma-pg
    environment:
      POSTGRES_DB: shopma
      POSTGRES_USER: shopma
      POSTGRES_PASSWORD: shopma
    ports:
      - "5432:5432"
    volumes:
      - shopma_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopma -d shopma"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: shopma-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopma
      SPRING_DATASOURCE_USERNAME: shopma
      SPRING_DATASOURCE_PASSWORD: shopma
    ports:
      - "8080:8080"

volumes:
  shopma_pgdata:
